/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:09:01 GMT 2024
 */

package hr.algebra.dal.webshop2024dal.Consts;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.dal.webshop2024dal.Consts.WebShopConsts;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WebShopConsts_ESTest extends WebShopConsts_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WebShopConsts webShopConsts0 = new WebShopConsts();
  }
}
