/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:36:16 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiDTO;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.api.webshop2024api.ApiDTO.DTOShoppingCart;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DTOShoppingCart_ESTest extends DTOShoppingCart_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart();
      String string0 = dTOShoppingCart0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart();
      dTOShoppingCart0.setUsername("");
      String string0 = dTOShoppingCart0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("", "");
      dTOShoppingCart0.setSessionId((String) null);
      String string0 = dTOShoppingCart0.getSessionId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("oA;]%n0-H!UXN%)g", "-C(R/3+Ry6$g34");
      assertEquals("-C(R/3+Ry6$g34", dTOShoppingCart0.getSessionId());
      
      dTOShoppingCart0.setSessionId("");
      dTOShoppingCart0.getSessionId();
      assertEquals("oA;]%n0-H!UXN%)g", dTOShoppingCart0.getUsername());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("", "");
      Long long0 = Long.getLong("", 0L);
      dTOShoppingCart0.setCartId(long0);
      Long long1 = dTOShoppingCart0.getCartId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("oA;]%n0-H!UXN%)g", "-C(R/3+Ry6$g34");
      Long long0 = new Long((-1L));
      dTOShoppingCart0.setCartId(long0);
      dTOShoppingCart0.getCartId();
      assertEquals("-C(R/3+Ry6$g34", dTOShoppingCart0.getSessionId());
      assertEquals("oA;]%n0-H!UXN%)g", dTOShoppingCart0.getUsername());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("oA;]%n0-H!UXN%)g", "-C(R/3+Ry6$g34");
      dTOShoppingCart0.getCartId();
      assertEquals("-C(R/3+Ry6$g34", dTOShoppingCart0.getSessionId());
      assertEquals("oA;]%n0-H!UXN%)g", dTOShoppingCart0.getUsername());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("oA;]%n0-H!UXN%)g", "-C(R/3+Ry6$g34");
      String string0 = dTOShoppingCart0.getUsername();
      assertEquals("-C(R/3+Ry6$g34", dTOShoppingCart0.getSessionId());
      assertEquals("oA;]%n0-H!UXN%)g", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart("oA;]%n0-H!UXN%)g", "-C(R/3+Ry6$g34");
      String string0 = dTOShoppingCart0.getSessionId();
      assertEquals("-C(R/3+Ry6$g34", string0);
      assertEquals("oA;]%n0-H!UXN%)g", dTOShoppingCart0.getUsername());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart();
      Long long0 = new Long(265L);
      dTOShoppingCart0.setCartId(long0);
      Long long1 = dTOShoppingCart0.getCartId();
      assertEquals(265L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart((String) null, (String) null);
      String string0 = dTOShoppingCart0.toString();
      assertEquals("DTOShoppingCart(cartId=null, username=null, sessionId=null)", string0);
  }
}
