/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:26:20 GMT 2024
 */

package hr.algebra.utils.ImageConverter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.IIOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ImageConverter_ESTest extends
    hr.algebra.utils.ImageConverter.ImageConverter_ESTest_2_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(367, 1493, "Multi-Release");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(0, 0, "");
      URL uRL0 = MockURL.getFtpExample();
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter((-1821), (-1821), "");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64((URL) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input == null!
         //
         verifyException("javax.imageio.ImageIO", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter((-1216), (-1216), "");
      try { 
        imageConverter0.convertToBase64("hr.algebra.utils.ImageConverter.ImageConverter");
        fail("Expecting exception: MalformedURLException");
      
      } catch(MalformedURLException e) {
         //
         // no protocol: hr.algebra.utils.ImageConverter.ImageConverter
         //
         verifyException("java.net.URL", e);
      }
  }

  /*
  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(482, 482, "Hys~I@Rt%zIF4UAL7^");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64((BufferedImage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // net/coobird/thumbnailator/Thumbnails
         //
         verifyException("hr.algebra.utils.ImageConverter.ImageConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "|");
      ImageConverter imageConverter0 = new ImageConverter(2007, 2007, "2j%t");
      URL uRL0 = MockURL.getHttpExample();
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // net/coobird/thumbnailator/Thumbnails
         //
         verifyException("hr.algebra.utils.ImageConverter.ImageConverter", e);
      }
  }

   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter((-87), (-87), "file:ojYSt");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64("file:ojYSt");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(2007, 2007, "2j%t");
      URL uRL0 = MockURL.getHttpExample();
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: IIOException");
      
      } catch(IIOException e) {
         //
         // Can't get input stream from URL!
         //
         verifyException("javax.imageio.ImageIO", e);
      }
  }
}
