/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:02:46 GMT 2024
 */

package hr.algebra.webshop2024.DTO;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.dal.webshop2024dal.Entity.Authority;
import hr.algebra.dal.webshop2024dal.Entity.User;
import hr.algebra.webshop2024.DTO.DTONotification;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DTONotification_ESTest extends DTONotification_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Long long0 = new Long(0L);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(0);
      LocalDateTime localDateTime1 = MockLocalDateTime.ofEpochSecond(0L, 0, zoneOffset0);
      DTONotification dTONotification0 = new DTONotification(long0, (User) null, "fc@7?aQUg*5KS3#", "/.+k-cw!m4p'Hf;>j}", localDateTime0, localDateTime1, false);
      assertFalse(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      ZoneId zoneId0 = ZoneId.systemDefault();
      LocalDateTime localDateTime1 = MockLocalDateTime.now(zoneId0);
      DTONotification dTONotification0 = new DTONotification((User) null, ", enabled=", "$UD=;GU:", localDateTime0, localDateTime1, true);
      assertTrue(dTONotification0.isViewed());
      assertEquals("$UD=;GU:", dTONotification0.getMessage());
      assertEquals(", enabled=", dTONotification0.getTitle());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Long long0 = new Long(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, "{w*Cy%f&9 QQ:W", ";", localDateTime0, localDateTime0, true);
      boolean boolean0 = dTONotification0.isViewed();
      assertTrue(boolean0);
      assertEquals("{w*Cy%f&9 QQ:W", dTONotification0.getTitle());
      assertEquals(";", dTONotification0.getMessage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long(0L);
      User user0 = new User();
      Set<Authority> set0 = user0.getAuthorities();
      User user1 = new User("{w*Cy%f&9 QQ:W", true, "", set0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user1, "{w*Cy%f&9 QQ:W", ";", localDateTime0, localDateTime0, true);
      dTONotification0.getUser();
      assertTrue(dTONotification0.isViewed());
      assertEquals(";", dTONotification0.getMessage());
      assertEquals("{w*Cy%f&9 QQ:W", dTONotification0.getTitle());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Long long0 = new Long((-1L));
      User user0 = new User();
      DTONotification dTONotification0 = new DTONotification(long0, user0, "P-%'vqjtqL0", "P-%'vqjtqL0", (LocalDateTime) null, (LocalDateTime) null, true);
      dTONotification0.getUser();
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, "{w*Cy%f&9 QQ:W", ";", localDateTime0, localDateTime0, true);
      String string0 = dTONotification0.getTitle();
      assertTrue(dTONotification0.isViewed());
      assertEquals(";", dTONotification0.getMessage());
      assertEquals("{w*Cy%f&9 QQ:W", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification((Long) null, user0, "", "", localDateTime0, localDateTime0, false);
      dTONotification0.getTitle();
      assertFalse(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Long long0 = Long.valueOf(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, (String) null, "User(username=", localDateTime0, localDateTime0, true);
      dTONotification0.getReadAt();
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = new Long(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, "{w*Cy%f&9 QQ:W", ";", localDateTime0, localDateTime0, true);
      dTONotification0.getNotificationId();
      assertEquals("{w*Cy%f&9 QQ:W", dTONotification0.getTitle());
      assertEquals(";", dTONotification0.getMessage());
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      Long long0 = new Long(389L);
      dTONotification0.setNotificationId(long0);
      Long long1 = dTONotification0.getNotificationId();
      assertEquals(389L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      Long long0 = new Long((-1L));
      dTONotification0.setNotificationId(long0);
      Long long1 = dTONotification0.getNotificationId();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Long long0 = Long.valueOf(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, (String) null, "User(username=", localDateTime0, localDateTime0, true);
      String string0 = dTONotification0.getMessage();
      assertNotNull(string0);
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      dTONotification0.setMessage("");
      String string0 = dTONotification0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(user0, "YO2sUNjKQ|", "YO2sUNjKQ|", localDateTime0, localDateTime0, true);
      dTONotification0.getCreatedAt();
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      Long long0 = dTONotification0.getNotificationId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      LocalDateTime localDateTime0 = dTONotification0.getCreatedAt();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      User user0 = dTONotification0.getUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      boolean boolean0 = dTONotification0.isViewed();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Long long0 = Long.valueOf(0L);
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(long0, user0, (String) null, "User(username=", localDateTime0, localDateTime0, true);
      String string0 = dTONotification0.getTitle();
      assertNull(string0);
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      LocalDateTime localDateTime0 = dTONotification0.getReadAt();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Long long0 = new Long(514L);
      User user0 = new User();
      DTONotification dTONotification0 = new DTONotification(long0, user0, (String) null, (String) null, (LocalDateTime) null, (LocalDateTime) null, true);
      dTONotification0.setTitle((String) null);
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DTONotification dTONotification0 = new DTONotification();
      String string0 = dTONotification0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Long long0 = new Long(514L);
      User user0 = new User();
      DTONotification dTONotification0 = new DTONotification(long0, user0, (String) null, (String) null, (LocalDateTime) null, (LocalDateTime) null, true);
      dTONotification0.setReadAt((LocalDateTime) null);
      assertTrue(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(user0, "hr.algebradal.webshop2024al.Entity.Authority", "hr.algebradal.webshop2024al.Entity.Authority", localDateTime0, localDateTime0, false);
      dTONotification0.setUser(user0);
      assertFalse(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(user0, "hr.algebradal.webshop2024al.Entity.Authority", "hr.algebradal.webshop2024al.Entity.Authority", localDateTime0, localDateTime0, false);
      dTONotification0.setViewed(false);
      assertFalse(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(user0, "hr.algebradal.webshop2024al.Entity.Authority", "hr.algebradal.webshop2024al.Entity.Authority", localDateTime0, localDateTime0, false);
      dTONotification0.setCreatedAt(localDateTime0);
      assertFalse(dTONotification0.isViewed());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      DTONotification dTONotification0 = new DTONotification(user0, "hr.algebradal.webshop2024al.Entity.Authority", "hr.algebradal.webshop2024al.Entity.Authority", localDateTime0, localDateTime0, false);
      String string0 = dTONotification0.toString();
      assertEquals("DTONotification(notificationId=null, user=User(username=null, password=null, enabled=false, email=null, authorities=[]), title=hr.algebradal.webshop2024al.Entity.Authority, message=hr.algebradal.webshop2024al.Entity.Authority, createdAt=2014-02-14T20:21:21.320, readAt=2014-02-14T20:21:21.320, viewed=false)", string0);
  }
}
