/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 19 09:00:48 GMT 2024
 */

package hr.algebra.utils.ImageConverter;

import org.evosuite.runtime.mock.java.lang.MockIllegalAccessException;
import org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException;
import org.evosuite.runtime.mock.java.lang.MockNullPointerException;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.IIOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ImageConverter_ESTest_2 extends
    hr.algebra.utils.ImageConverter.ImageConverter_ESTest_2_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(207, 2462, (String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(0, 0, "nv> 52k");
      URL uRL0 = MockURL.getFtpExample();
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(0, 0, "");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64((URL) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input == null!
         //
         verifyException("javax.imageio.ImageIO", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(1, 1, "jar:file:context.jar!/");
      try { 
        imageConverter0.convertToBase64("\"ZG");
        fail("Expecting exception: MalformedURLException");
      
      } catch(MalformedURLException e) {
         //
         // no protocol: \"ZG
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(23, 23, "rC}{R#0Q+/~S`oW");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64((BufferedImage) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // net/coobird/thumbnailator/Thumbnails
         //
         verifyException("hr.algebra.utils.ImageConverter.ImageConverter", e);
      } catch (MockNullPointerException e) {
        verifyException("net.coobird.thumbnailator.tasks.io.BufferedImageSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "*/");
      ImageConverter imageConverter0 = new ImageConverter((-4093), (-4093), "sDP");
      URL uRL0 = MockURL.getHttpExample();
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // net/coobird/thumbnailator/Thumbnails
         //
         verifyException("hr.algebra.utils.ImageConverter.ImageConverter", e);
      } catch(MockIllegalArgumentException ex) {
        verifyException("net.coobird.thumbnailator.Thumbnails", ex);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter(1701, 1701, "file::");
      // Undeclared exception!
      try { 
        imageConverter0.convertToBase64("file::");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ImageConverter imageConverter0 = new ImageConverter((-4093), (-4093), "sDP");
      URL uRL0 = MockURL.getHttpExample();
      try { 
        imageConverter0.convertToBase64(uRL0);
        fail("Expecting exception: IIOException");
      
      } catch(IIOException e) {
         //
         // Can't get input stream from URL!
         //
         verifyException("javax.imageio.ImageIO", e);
      }
  }
}
