/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jul 18 22:44:01 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiMapper;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CartItemMapperImpl_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "hr.algebra.api.webshop2024api.ApiMapper.CartItemMapperImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/user/workdir"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CartItemMapperImpl_ESTest_scaffolding.class.getClassLoader() ,
      "hr.algebra.api.webshop2024api.ApiDTO.DTOProduct",
      "hr.algebra.dal.webshop2024dal.Entity.Product",
      "hr.algebra.dal.webshop2024dal.Entity.Category",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOShoppingCart",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOSubcategory",
      "hr.algebra.dal.webshop2024dal.Entity.CartItem",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOCategory",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOCartItem",
      "hr.algebra.api.webshop2024api.ApiMapper.CartItemMapper",
      "hr.algebra.dal.webshop2024dal.Entity.ShoppingCart",
      "hr.algebra.dal.webshop2024dal.Entity.Image",
      "hr.algebra.dal.webshop2024dal.Entity.Subcategory",
      "hr.algebra.api.webshop2024api.ApiMapper.CartItemMapperImpl"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CartItemMapperImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "hr.algebra.api.webshop2024api.ApiMapper.CartItemMapperImpl",
      "hr.algebra.dal.webshop2024dal.Entity.ShoppingCart",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOShoppingCart",
      "hr.algebra.dal.webshop2024dal.Entity.Product",
      "hr.algebra.dal.webshop2024dal.Entity.CartItem",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOCartItem",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOProduct",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOCategory",
      "hr.algebra.dal.webshop2024dal.Entity.Category",
      "hr.algebra.api.webshop2024api.ApiDTO.DTOSubcategory",
      "hr.algebra.dal.webshop2024dal.Entity.Subcategory",
      "hr.algebra.dal.webshop2024dal.Entity.Image"
    );
  }
}
