/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:08:48 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiMapper;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.api.webshop2024api.ApiDTO.DTOCategory;
import hr.algebra.api.webshop2024api.ApiMapper.CategoryMapperImpl;
import hr.algebra.dal.webshop2024dal.Entity.Category;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CategoryMapperImpl_ESTest extends CategoryMapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CategoryMapperImpl categoryMapperImpl0 = new CategoryMapperImpl();
      Category category0 = categoryMapperImpl0.DTOCategoryToCategory((DTOCategory) null);
      assertNull(category0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CategoryMapperImpl categoryMapperImpl0 = new CategoryMapperImpl();
      DTOCategory dTOCategory0 = categoryMapperImpl0.CategoryItemToDTOCategory((Category) null);
      assertNull(dTOCategory0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CategoryMapperImpl categoryMapperImpl0 = new CategoryMapperImpl();
      DTOCategory dTOCategory0 = new DTOCategory((String) null);
      Category category0 = categoryMapperImpl0.DTOCategoryToCategory(dTOCategory0);
      DTOCategory dTOCategory1 = categoryMapperImpl0.CategoryItemToDTOCategory(category0);
      assertNotSame(dTOCategory0, dTOCategory1);
  }
}
