/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:41:11 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiMapper;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.api.webshop2024api.ApiDTO.DTOOrder;
import hr.algebra.api.webshop2024api.ApiMapper.OrderMapperImpl;
import hr.algebra.dal.webshop2024dal.Entity.Order;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OrderMapperImpl_ESTest extends OrderMapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrderMapperImpl orderMapperImpl0 = new OrderMapperImpl();
      Order order0 = orderMapperImpl0.DTOOrderToOrder((DTOOrder) null);
      assertNull(order0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrderMapperImpl orderMapperImpl0 = new OrderMapperImpl();
      DTOOrder dTOOrder0 = orderMapperImpl0.OrderToDTOOrder((Order) null);
      assertNull(dTOOrder0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrderMapperImpl orderMapperImpl0 = new OrderMapperImpl();
      DTOOrder dTOOrder0 = new DTOOrder();
      Order order0 = orderMapperImpl0.DTOOrderToOrder(dTOOrder0);
      DTOOrder dTOOrder1 = orderMapperImpl0.OrderToDTOOrder(order0);
      assertNotSame(dTOOrder0, dTOOrder1);
  }
}
