/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 21:49:41 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiMapper;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.api.webshop2024api.ApiDTO.DTOShoppingCart;
import hr.algebra.api.webshop2024api.ApiMapper.ShoppingCartImageImpl;
import hr.algebra.dal.webshop2024dal.Entity.ShoppingCart;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShoppingCartImageImpl_ESTest extends ShoppingCartImageImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ShoppingCartImageImpl shoppingCartImageImpl0 = new ShoppingCartImageImpl();
      ShoppingCart shoppingCart0 = shoppingCartImageImpl0.DTOShoppingCartToShoppingCart((DTOShoppingCart) null);
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ShoppingCartImageImpl shoppingCartImageImpl0 = new ShoppingCartImageImpl();
      DTOShoppingCart dTOShoppingCart0 = new DTOShoppingCart();
      ShoppingCart shoppingCart0 = shoppingCartImageImpl0.DTOShoppingCartToShoppingCart(dTOShoppingCart0);
      assertNull(shoppingCart0.getUsername());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ShoppingCartImageImpl shoppingCartImageImpl0 = new ShoppingCartImageImpl();
      DTOShoppingCart dTOShoppingCart0 = shoppingCartImageImpl0.ShoppingCartToDTOShoppingCart((ShoppingCart) null);
      assertNull(dTOShoppingCart0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ShoppingCartImageImpl shoppingCartImageImpl0 = new ShoppingCartImageImpl();
      ShoppingCart shoppingCart0 = new ShoppingCart();
      DTOShoppingCart dTOShoppingCart0 = shoppingCartImageImpl0.ShoppingCartToDTOShoppingCart(shoppingCart0);
      assertNull(dTOShoppingCart0.getCartId());
  }
}
