/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:40:43 GMT 2024
 */

package hr.algebra.api.webshop2024api.ApiMapper;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.api.webshop2024api.ApiDTO.DTOUserConnection;
import hr.algebra.api.webshop2024api.ApiMapper.UserConnectionMapperImpl;
import hr.algebra.dal.webshop2024dal.Entity.UserConnection;
import java.time.LocalDateTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserConnectionMapperImpl_ESTest extends UserConnectionMapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserConnectionMapperImpl userConnectionMapperImpl0 = new UserConnectionMapperImpl();
      UserConnection userConnection0 = userConnectionMapperImpl0.DTOUserConnectionToUserConnection((DTOUserConnection) null);
      assertNull(userConnection0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserConnectionMapperImpl userConnectionMapperImpl0 = new UserConnectionMapperImpl();
      DTOUserConnection dTOUserConnection0 = new DTOUserConnection((LocalDateTime) null, "");
      UserConnection userConnection0 = userConnectionMapperImpl0.DTOUserConnectionToUserConnection(dTOUserConnection0);
      assertNull(userConnection0.getUsername());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserConnectionMapperImpl userConnectionMapperImpl0 = new UserConnectionMapperImpl();
      DTOUserConnection dTOUserConnection0 = userConnectionMapperImpl0.UserConnectionToDTOUserConnection((UserConnection) null);
      assertNull(dTOUserConnection0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserConnectionMapperImpl userConnectionMapperImpl0 = new UserConnectionMapperImpl();
      UserConnection userConnection0 = new UserConnection("", (LocalDateTime) null, "hr.algebra.dal.webshop2024dal.Entity.UserConnection");
      DTOUserConnection dTOUserConnection0 = userConnectionMapperImpl0.UserConnectionToDTOUserConnection(userConnection0);
      assertEquals("", dTOUserConnection0.getUsername());
  }
}
