/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:39:00 GMT 2024
 */

package hr.algebra.dal.webshop2024dal.Entity;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.dal.webshop2024dal.Entity.Category;
import hr.algebra.dal.webshop2024dal.Entity.Subcategory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subcategory_ESTest extends Subcategory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subcategory subcategory0 = new Subcategory((String) null, (Category) null);
      Long long0 = new Long(0L);
      subcategory0.setSubcategoryId(long0);
      Long long1 = subcategory0.getSubcategoryId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Long long0 = new Long(1169L);
      Category category0 = new Category(long0, ",hJM 4VbjDP4]oQM$'");
      Subcategory subcategory0 = new Subcategory(long0, ",hJM 4VbjDP4]oQM$'", category0);
      Long long1 = subcategory0.getSubcategoryId();
      assertEquals(1169L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Long long0 = new Long((-96L));
      Category category0 = new Category();
      Subcategory subcategory0 = new Subcategory(long0, ", name=", category0);
      Long long1 = subcategory0.getSubcategoryId();
      assertEquals((-96L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long((-2276L));
      Category category0 = new Category();
      Subcategory subcategory0 = new Subcategory(long0, "E# k$c`UqX$xo8r4y@", category0);
      String string0 = subcategory0.getName();
      assertEquals("E# k$c`UqX$xo8r4y@", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subcategory subcategory0 = new Subcategory();
      subcategory0.setName("");
      String string0 = subcategory0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long((-2276L));
      Category category0 = new Category();
      Subcategory subcategory0 = new Subcategory(long0, "E# k$c`UqX$xo8r4y@", category0);
      Category category1 = subcategory0.getCategory();
      assertSame(category0, category1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subcategory subcategory0 = new Subcategory();
      Long long0 = subcategory0.getSubcategoryId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subcategory subcategory0 = new Subcategory();
      String string0 = subcategory0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = new Long(40L);
      Subcategory subcategory0 = new Subcategory(long0, "M#KLH6QXGKC", (Category) null);
      subcategory0.setCategory((Category) null);
      assertEquals("M#KLH6QXGKC", subcategory0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subcategory subcategory0 = new Subcategory();
      Category category0 = subcategory0.getCategory();
      assertNull(category0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Long long0 = new Long((-854L));
      Subcategory subcategory0 = new Subcategory(long0, "m");
      subcategory0.setSubcategoryId(long0);
      assertEquals((-854L), (long)subcategory0.getSubcategoryId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Long long0 = new Long(40L);
      Subcategory subcategory0 = new Subcategory(long0, "M#KLH6QXGKC", (Category) null);
      String string0 = subcategory0.toString();
      assertEquals("Subcategory(subcategoryId=40, name=M#KLH6QXGKC, category=null)", string0);
  }
}
