/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:11:39 GMT 2024
 */

package hr.algebra.dal.webshop2024dal.Entity;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.dal.webshop2024dal.Entity.UserConnection;
import java.time.LocalDateTime;
import java.time.Month;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserConnection_ESTest extends UserConnection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      UserConnection userConnection0 = new UserConnection(localDateTime0, "");
      String string0 = userConnection0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserConnection userConnection0 = new UserConnection((LocalDateTime) null, "");
      userConnection0.setUsername("");
      String string0 = userConnection0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Month month0 = Month.JANUARY;
      LocalDateTime localDateTime0 = MockLocalDateTime.of(1, month0, 1, 1, 1);
      UserConnection userConnection0 = new UserConnection("9R|3:ZGBAn}GQkHD6VI", localDateTime0, "");
      userConnection0.getLastConnection();
      assertEquals("", userConnection0.getIpAddress());
      assertEquals("9R|3:ZGBAn}GQkHD6VI", userConnection0.getUsername());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Month month0 = Month.JANUARY;
      LocalDateTime localDateTime0 = MockLocalDateTime.of(1, month0, 1, 1, 1);
      UserConnection userConnection0 = new UserConnection("9R|3:ZGBAn}GQkHD6VI", localDateTime0, "");
      assertEquals("", userConnection0.getIpAddress());
      
      userConnection0.setIpAddress("9R|3:ZGBAn}GQkHD6VI");
      userConnection0.getIpAddress();
      assertEquals("9R|3:ZGBAn}GQkHD6VI", userConnection0.getUsername());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserConnection userConnection0 = new UserConnection((LocalDateTime) null, "");
      String string0 = userConnection0.getIpAddress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserConnection userConnection0 = new UserConnection((LocalDateTime) null, "");
      LocalDateTime localDateTime0 = userConnection0.getLastConnection();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UserConnection userConnection0 = new UserConnection("Et{mKG@ [ZE)M", (LocalDateTime) null, "Et{mKG@ [ZE)M");
      String string0 = userConnection0.getUsername();
      assertEquals("Et{mKG@ [ZE)M", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Month month0 = Month.JANUARY;
      LocalDateTime localDateTime0 = MockLocalDateTime.of(1, month0, 1, 1, 1);
      UserConnection userConnection0 = new UserConnection("9R|3:ZGBAn}GQkHD6VI", localDateTime0, "");
      userConnection0.setLastConnection(localDateTime0);
      assertEquals("9R|3:ZGBAn}GQkHD6VI", userConnection0.getUsername());
      assertEquals("", userConnection0.getIpAddress());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      UserConnection userConnection0 = new UserConnection();
      String string0 = userConnection0.getIpAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      UserConnection userConnection0 = new UserConnection(localDateTime0, "");
      String string0 = userConnection0.toString();
      assertEquals("UserConnection(username=null, lastConnection=2014-02-14T20:21:21.320, ipAddress=)", string0);
  }
}
