package webshop2024api;

import static io.restassured.RestAssured.given;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.numberMatches;
import static org.evomaster.client.java.controller.expect.ExpectationHandler.expectationHandler;
import static org.evomaster.client.java.sql.dsl.SqlDsl.sql;
import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.assertNotNull;

import hr.algebra.api.webshop2024api.EvoMasterDriver;
import io.restassured.RestAssured;
import io.restassured.config.JsonConfig;
import io.restassured.path.json.config.JsonPathConfig;
import io.restassured.response.ValidatableResponse;
import java.util.Arrays;
import java.util.List;
import org.evomaster.client.java.controller.SutHandler;
import org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import org.evomaster.client.java.controller.api.dto.database.operations.InsertionResultsDto;
import org.evomaster.client.java.controller.expect.ExpectationHandler;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;




/**
 * This file was automatically generated by EvoMaster on 2024-07-17T23:27:49.165+02:00[Europe/Belgrade]
 * <br>
 * The generated test suite contains 7 tests
 * <br>
 * Covered targets: 73
 * <br>
 * Used time: 2h 0m 2s
 * <br>
 * Needed budget for current results: 83%
 * <br>
 * This file contains test cases that represent failed calls, but not indicative of faults.
 */
public class EvoMaster_others_Test {

    
    private static final SutHandler controller = new EvoMasterDriver();
    private static String baseUrlOfSut;
    /** [ems] - expectations master switch - is the variable that activates/deactivates expectations individual test cases
    * by default, expectations are turned off. The variable needs to be set to [true] to enable expectations
    */
    private static boolean ems = false;
    /**
    * sco - supported code oracle - checking that the response status code is among those supported according to the schema
    */
    private static boolean sco = false;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetDatabase(Arrays.asList("CATEGORIES","SUBCATEGORIES","PRODUCTS","CART_ITEMS","ORDER_ITEMS","SHOPPING_CART","IMAGE"));
        controller.resetStateOfSUT();
    }
    
    
    
    
    @Test(timeout = 60000)
    public void test_0() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("SHOPPING_CART", 464L)
            .and().insertInto("CATEGORIES", 463L)
                .d("NAME", "\"mumdUR\"")
            .and().insertInto("SUBCATEGORIES", 462L)
                .d("NAME", "\"_EM_63086_XYZ_\"")
                .r("CATEGORY_ID", 463L)
            .and().insertInto("IMAGE", 461L)
                .d("IMAGE_B64", "\"tXwoU\"")
            .and().insertInto("PRODUCTS", 460L)
                .d("NAME", "\"Y5bj2ZLyJVe1m5\"")
                .d("PRICE", "0.6074437")
                .r("SUBCATEGORY_ID", 462L)
            .and().insertInto("CART_ITEMS", 459L)
                .d("QUANTITY", "42")
                .r("PRODUCT_ID", 460L)
                .r("CART_ID", 464L)
            .and().insertInto("SHOPPING_CART", 470L)
            .and().insertInto("CATEGORIES", 469L)
                .d("NAME", "\"CjT\"")
            .and().insertInto("SUBCATEGORIES", 468L)
                .d("NAME", "\"ukb0RV\"")
                .r("CATEGORY_ID", 463L)
            .and().insertInto("IMAGE", 467L)
                .d("IMAGE_B64", "\"0O5XbIKtfwTN6Dw\"")
            .and().insertInto("PRODUCTS", 466L)
                .d("NAME", "\"NfPI1fiCq\"")
                .d("PRICE", "0.83685005")
                .r("SUBCATEGORY_ID", 468L)
            .and().insertInto("CART_ITEMS", 465L)
                .d("QUANTITY", "641")
                .r("PRODUCT_ID", 460L)
                .r("CART_ID", 470L)
            .and().insertInto("SHOPPING_CART", 476L)
            .and().insertInto("CATEGORIES", 475L)
                .d("NAME", "\"uyI\"")
            .and().insertInto("SUBCATEGORIES", 474L)
                .d("NAME", "\"hnwfjMc\"")
                .r("CATEGORY_ID", 475L)
            .and().insertInto("IMAGE", 473L)
                .d("IMAGE_B64", "\"KlBaZ\"")
            .and().insertInto("PRODUCTS", 472L)
                .d("NAME", "\"_EM_63087_XYZ_\"")
                .d("PRICE", "0.0")
                .r("SUBCATEGORY_ID", 468L)
            .and().insertInto("CART_ITEMS", 471L)
                .d("QUANTITY", "524793")
                .r("PRODUCT_ID", 466L)
                .r("CART_ID", 476L)
            .and().insertInto("SHOPPING_CART", 482L)
            .and().insertInto("CATEGORIES", 481L)
                .d("NAME", "\"Mg9UEgUCB\"")
            .and().insertInto("SUBCATEGORIES", 480L)
                .d("NAME", "\"iDzIN\"")
                .r("CATEGORY_ID", 469L)
            .and().insertInto("IMAGE", 479L)
                .d("IMAGE_B64", "\"Ipe_KJpS7RTaWO\"")
            .and().insertInto("PRODUCTS", 478L)
                .d("NAME", "\"vvrdy\"")
                .d("PRICE", "1.1147908")
                .r("SUBCATEGORY_ID", 468L)
            .and().insertInto("CART_ITEMS", 477L)
                .d("QUANTITY", "122")
                .r("PRODUCT_ID", 466L)
                .r("CART_ID", 470L)
            .and().insertInto("SHOPPING_CART", 488L)
            .and().insertInto("CATEGORIES", 487L)
                .d("NAME", "\"AwCSXfThOAQsu69\"")
            .and().insertInto("SUBCATEGORIES", 486L)
                .d("NAME", "\"_EM_63088_XYZ_\"")
                .r("CATEGORY_ID", 463L)
            .and().insertInto("IMAGE", 485L)
                .d("IMAGE_B64", "\"vd84Pl5\"")
            .and().insertInto("PRODUCTS", 484L)
                .d("NAME", "\"I8c\"")
                .d("PRICE", "0.48274288")
                .r("SUBCATEGORY_ID", 474L)
            .and().insertInto("CART_ITEMS", 483L)
                .d("QUANTITY", "939")
                .r("PRODUCT_ID", 478L)
                .r("CART_ID", 488L)
            .and().insertInto("SHOPPING_CART", 4934L)
                .d("SESSION_ID", "\"\"")
                .d("USERNAME", "\"_EM_63089_XYZ_\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/webShopApi/cartItems/findByUsername/jODiQ%5CW8zsZyk")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_1() throws Exception {
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"subcategoryId\": 213, " + 
                    " \"name\": \"\" " + 
                    " } ")
                .post(baseUrlOfSut + "/webShopApi/subcategories?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'name'", containsString("Subcategory name is required!"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_2() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CATEGORIES", 558L)
                .d("NAME", "\"_EM_5126_XYZ_\"")
            .and().insertInto("SUBCATEGORIES", 557L)
                .d("NAME", "\"_EM_5127_XYZ_\"")
                .r("CATEGORY_ID", 558L)
            .and().insertInto("CATEGORIES", 560L)
                .d("NAME", "\"_EM_5128_XYZ_\"")
            .and().insertInto("SUBCATEGORIES", 559L)
                .d("NAME", "\"vrNpSPJZDX\"")
                .r("CATEGORY_ID", 560L)
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"\" " + 
                    " } ")
                .post(baseUrlOfSut + "/webShopApi/categories?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'name'", containsString("Category name is required"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_3() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("SHOPPING_CART", 1839L)
            .and().insertInto("CATEGORIES", 1838L)
                .d("NAME", "\"nnazSZn_Wc0OVhzt_\"")
            .and().insertInto("SUBCATEGORIES", 1837L)
                .d("NAME", "\"HrvNMjdtGK8\"")
                .r("CATEGORY_ID", 1838L)
            .and().insertInto("IMAGE", 1836L)
                .d("IMAGE_B64", "\"_EM_64158_XYZ_G\"")
            .and().insertInto("PRODUCTS", 1835L)
                .d("NAME", "\"TzJDd\"")
                .d("PRICE", "0.07461912")
                .r("SUBCATEGORY_ID", 1837L)
            .and().insertInto("CART_ITEMS", 1834L)
                .d("QUANTITY", "769")
                .r("PRODUCT_ID", 1835L)
                .r("CART_ID", 1839L)
            .and().insertInto("SHOPPING_CART", 9417L)
                .d("SESSION_ID", "\"T2dBseBLLNz\"")
                .d("USERNAME", "\"RB5sBTfPdkqr6O\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"subcategoryId\": 980, " + 
                    " \"name\": \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/webShopApi/subcategories/980")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'name'", containsString("Subcategory name is required!"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_4() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CATEGORIES", 2319L)
                .d("NAME", "\"_EM_6853_XYZ_\"")
            .and().insertInto("CATEGORIES", 2320L)
                .d("NAME", "\"HnUdAO34wIo\"")
            .and().insertInto("CATEGORIES", 2321L)
                .d("NAME", "\"_EM_7664_XYZ_\"")
            .and().insertInto("CATEGORIES", 2322L)
                .d("NAME", "\"_EM_7665_XYZ_\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"categoryId\": 93, " + 
                    " \"name\": \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/webShopApi/categories/93?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'name'", containsString("Category name is required"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_5() throws Exception {
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"_EM_43_XYZ_\", " + 
                    " \"description\": \"_EM_44_XYZ_\", " + 
                    " \"price\": 0.6966392838931554, " + 
                    " \"subcategory\": { " + 
                    " \"subcategoryId\": 944607605, " + 
                    " \"name\": \"MN8UkkMI5et_1\" " + 
                    " }, " + 
                    " \"imageUrl\": \"_EM_46_XYZ_\" " + 
                    " } ")
                .put(baseUrlOfSut + "/webShopApi/products/798?EMextraParam123=_EM_48_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'price'", containsString("Price must not exceed 6 digits in the integer part and 2 digits in the fraction part"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }
    
    
    @Test(timeout = 60000)
    public void test_6() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CATEGORIES", 2663L)
                .d("NAME", "\"_EM_51719_XYZ_\"")
            .and().insertInto("CATEGORIES", 2664L)
                .d("NAME", "\"5_V\"")
            .and().insertInto("CATEGORIES", 2665L)
                .d("NAME", "\"_xR\"")
            .and().insertInto("CATEGORIES", 2666L)
                .d("NAME", "\"_EM_51720_XYZ_\"")
            .and().insertInto("SHOPPING_CART", 2837L)
                .d("SESSION_ID", "NULL")
                .d("USERNAME", "\"CkM3kQk0zD\"")
            .and().insertInto("SHOPPING_CART", 2838L)
                .d("SESSION_ID", "\"Y55B7dBsHV4xTY\"")
                .d("USERNAME", "\"\"")
            .and().insertInto("CATEGORIES", 3690L)
                .d("NAME", "\"\"")
            .and().insertInto("SUBCATEGORIES", 3689L)
                .d("NAME", "\"U\"")
                .r("CATEGORY_ID", 2663L)
            .and().insertInto("CATEGORIES", 3692L)
                .d("NAME", "\"MSKcZb4V2Sq4m4mV\"")
            .and().insertInto("SUBCATEGORIES", 3691L)
                .d("NAME", "\"Ls9CDHMLJrHhCpp\"")
                .r("CATEGORY_ID", 2663L)
            .and().insertInto("CATEGORIES", 3694L)
                .d("NAME", "\"6\"")
            .and().insertInto("SUBCATEGORIES", 3693L)
                .d("NAME", "\"_EM_51721_XYZ_\"")
                .r("CATEGORY_ID", 2665L)
            .and().insertInto("CATEGORIES", 7546L)
                .d("NAME", "\"_EM_51722_XYZ_\"")
            .and().insertInto("SUBCATEGORIES", 7545L)
                .d("NAME", "\"_EM_51723_XYZ_\"")
                .r("CATEGORY_ID", 2664L)
            .and().insertInto("IMAGE", 7544L)
                .d("IMAGE_B64", "\"m64m3N\"")
            .and().insertInto("PRODUCTS", 7543L)
                .d("DESCRIPTION", "\"_EM_51724_XYZ_\"")
                .d("NAME", "\"xHEyf1pk\"")
                .d("PRICE", "0.4686513")
                .r("IMAGE_ID", 7544L)
                .r("SUBCATEGORY_ID", 7545L)
            .and().insertInto("CATEGORIES", 7550L)
                .d("NAME", "\"_EM_51725_XYZ_\"")
            .and().insertInto("SUBCATEGORIES", 7549L)
                .d("NAME", "\"_EM_51726_XYZ_\"")
                .r("CATEGORY_ID", 7546L)
            .and().insertInto("IMAGE", 7548L)
                .d("IMAGE_B64", "\"6d_S\"")
            .and().insertInto("PRODUCTS", 7547L)
                .d("DESCRIPTION", "NULL")
                .d("NAME", "\"D7UF9O3rLr\"")
                .d("PRICE", "0.9569674")
                .r("IMAGE_ID", 7544L)
                .r("SUBCATEGORY_ID", 7545L)
            .and().insertInto("CATEGORIES", 7554L)
                .d("NAME", "\"UqZWW2fXylHazU\"")
            .and().insertInto("SUBCATEGORIES", 7553L)
                .d("NAME", "\"XOUYF2Z\"")
                .r("CATEGORY_ID", 3694L)
            .and().insertInto("IMAGE", 7552L)
                .d("IMAGE_B64", "\"FliIiAKKn\"")
            .and().insertInto("PRODUCTS", 7551L)
                .d("DESCRIPTION", "\"1t9QvS06AdXtpp7\"")
                .d("NAME", "\"3tnWpJxqe6hoAWv\"")
                .d("PRICE", "0.66462415")
                .d("IMAGE_ID", "NULL")
                .r("SUBCATEGORY_ID", 3693L)
            .and().insertInto("CATEGORIES", 7558L)
                .d("NAME", "\"7qurAmoSsdiA\"")
            .and().insertInto("SUBCATEGORIES", 7557L)
                .d("NAME", "\"oKnRlOn\"")
                .r("CATEGORY_ID", 3692L)
            .and().insertInto("IMAGE", 7556L)
                .d("IMAGE_B64", "\"pI\"")
            .and().insertInto("PRODUCTS", 7555L)
                .d("DESCRIPTION", "\"_EM_51727_XYZ_\"")
                .d("NAME", "\"MHccGHffvm\"")
                .d("PRICE", "0.74661034")
                .d("IMAGE_ID", "NULL")
                .r("SUBCATEGORY_ID", 7553L)
            .and().insertInto("CATEGORIES", 7562L)
                .d("NAME", "\"_EM_51728_XYZ_\"")
            .and().insertInto("SUBCATEGORIES", 7561L)
                .d("NAME", "\"_EM_51729_XYZ_\"")
                .r("CATEGORY_ID", 2666L)
            .and().insertInto("IMAGE", 7560L)
                .d("IMAGE_B64", "\"duWiHcrslgW\"")
            .and().insertInto("PRODUCTS", 7559L)
                .d("DESCRIPTION", "\"ICZMIvmxZ\"")
                .d("NAME", "\"_EM_51730_XYZ_\"")
                .d("PRICE", "0.9633604")
                .r("IMAGE_ID", 7560L)
                .r("SUBCATEGORY_ID", 3693L)
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        ExpectationHandler expectationHandler = expectationHandler();
        
        ValidatableResponse res_0 = given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": 229, " + 
                    " \"name\": \"3Q\", " + 
                    " \"description\": \"V3ab6ezX7E7FV\", " + 
                    " \"price\": 0.06884456409783435, " + 
                    " \"subcategory\": { " + 
                    " \"name\": \"USenfcfW\", " + 
                    " \"category\": { " + 
                    " \"name\": \"6ynYWuxjw\" " + 
                    " } " + 
                    " }, " + 
                    " \"imageUrl\": \"zepKP\", " + 
                    " \"b64image\": \"TlJA9n_wa9T\" " + 
                    " } ")
                .post(baseUrlOfSut + "/webShopApi/products")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400.0))
                .body("'message'", containsString("Validation failed"))
                .body("'errors'.'price'", containsString("Price must not exceed 6 digits in the integer part and 2 digits in the fraction part"));
        
        expectationHandler.expect(ems)
            .that(sco, Arrays.asList(200).contains(res_0.extract().statusCode()));
    }


}
